- Fix bug when arch=both used - Add sourcing configurations - Add an option to use default 'MIRRORLIST' urpmi source - Add more informational messages

diff --git a/src/zeynep b/src/zeynep
--- a/src/zeynep
+++ b/src/zeynep
@@ -39,7 +39,7 @@ export TOP_PID=$$
 ####################################################################################################################################################
 # Make sure that we have only one log file:
 rm -f ${TMPDIR}/zeynep*.log 2>&1
-log_file="$(mktemp -t --suffix=".log" zeynep-builder.XXXXXXXXXX )"
+log_file="$(mktemp -t --suffix=".log" zeynep.XXXXXXXXXX )"
 #mkfifo ${log_file}.pipe
 #sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK(]//g" | sed 's/\x1b(B//g' | tee < ${log_file}.pipe ${log_file} & 
 #exec &> ${log_file}.pipe
@@ -52,7 +52,6 @@ exec &> >(tee -a "$log_file"; sed -i -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK
 ####################################################################################################################################################
 
 if [[ ${mga_version} != "cauldron" && ${mga_version} < 5 ]]; then urpmi_options+=("--no-suggests"); else urpmi_options+=("--no-recommends"); fi
-
 
 ####################################################################################################################################################
 plain () {
@@ -75,7 +74,7 @@ error2 () {
 # Function to display localized and colorized information messages
 ####################################################################################################################################################
 	local mesg=$1; shift
-	printf "${RED}==>$(gettext "NOT CRITICAL ERROR :: ")${ALL_OFF}${BOLD}${YELLOW} ${mesg}${ALL_OFF}\n" "$@" >&2
+	printf "${RED}==> $(gettext "NOT CRITICAL ERROR :: ")${ALL_OFF}${BOLD}${YELLOW} ${mesg}${ALL_OFF}\n" "$@" >&2
 }
 
 ####################################################################################################################################################
@@ -142,6 +141,7 @@ plain "$(gettext " -g        - Generate a chroot tarball which is used for build
 plain "$(gettext " -s        - Exact path/name of the srpm file. E.g. /home/user/foo-1.0-1.mga4.src.rpm")"
 plain "$(gettext " -D        - Temporary directory for chroot environment. Can be used with '-g' option. Default: %s")" "${TMPDIR}"
 plain "$(gettext " -d        - URL to retrive a set of media from a distribution.Uses 'urpmi.addmedia --distrib'. Default: MIRRORLIST")"
+plain "$(gettext " -z        - Force zeynep to not use given distrib media with -d switch/or from config file and default to MIRRORLIST")"
 plain "$(gettext " -c        - RPM cache directory which will be used for save time/bandwith. Default: Disabled")"
 plain "$(gettext " -M        - URL to retrive packages from. E.g. 'www.someurl.org/pub/mageia/4/media/i586'. Default: Disabled")"
 plain "$(gettext " -p        - Packages names to be installed in chroot. This option must be used with '-g' option and each package must be seperated by a space in quotes. E.g. 'locales-tr wget' Default: Disabled")"
@@ -210,7 +210,7 @@ if [ -n "${tidy_cache}" ] && [ -e ${cachedir} ]; then
     run_command "sudo rpm-tidy -f --dir="${cachedir}"" || warning "$(gettext "Zeynep failed to delete older rpms in %s using rpm-tidy utility. This is not critical. However you will have older versions/releases of same packages in the same directory. Please check %s for possible errors. Exiting...")" "${cachedir}" "${log_file}"
 fi
 
-if [ -n "${tidy_upload_rpms_dir}" ] && [ -e ${uploaddir} ]; then
+if [[ -z ${generate_tarball} && -n "${tidy_upload_rpms_dir}" ]] && [ -e ${uploaddir} ]; then
     run_command "sudo rpm-tidy  -f --dir="${uploaddir}"" || warning "$(gettext "Zeynep failed to delete older rpms in %s using rpm-tidy utility. This is not critical. However you will have older versions/releases of same packages in the same directory. Please check %s for possible errors. Exiting...")" "${uploaddir}" "${log_file}"
 fi
 
@@ -224,15 +224,20 @@ unclean_temp () {
 
 if [[ -z ${noclean} ]]; then
     if mount | grep ${chrootdir}; then
-        msg "$(gettext "%s won't be deleted. Please remove it manually.")" "${chrootdir}"
+        msg "$(gettext "%s won't be deleted. Please remove it manually.")" "${tempdir}"
     else
-        msg "$(gettext "Deleting %s")" "${chrootdir}"
-        ( run_command "sudo rm -fr ${tempdir}" && msg "$(gettext "... DONE!")" ) || ( error "$(gettext "An error occured during deleting %s. Please delete it manually.")" "${tempdir}" )
+        msg "$(gettext "Deleting %s")" "${tempdir}"
+        ( run_command "sudo rm -fr ${tempdir}" && msg "$(gettext "... DONE!")" ) || error "$(gettext "An error occured during deleting %s. Please delete it manually.")" "${tempdir}"
     fi
 else
     msg "$(gettext "%s won't be deleted. Please remove it manually.")" "${chrootdir}"
 fi
 
+# We must unset some variable for future uses. Else it would be invoked twice...
+unset tempdir
+unset tarball
+unset cachedir
+unset urpmi_options_array
 }
 
 ####################################################################################################################################################
@@ -261,7 +266,7 @@ exit_function () {
 ####################################################################################################################################################
 
 unmount_necessary_dirs
-run_command "kill -s TERM ${TOP_PID} && exit 1"
+kill -s TERM ${TOP_PID} && exit 1
 
 }
 
@@ -353,6 +358,8 @@ if [[ -n ${use_cache} && -d ${cachedir} ]];then
     else
         error2 "$(gettext "Failed to create mandatory %s directory for rpm cache usage. Zeynep will continue without cache enabled.")" "${chrootdir}/var/cache/urpmi/rpms" && return 1
     fi
+else
+    if [[ ! -d ${cachedir} ]]; then error2 "$(gettext "%s cache directory can not be found. Zeynep will continue without cache enabled.")" "${cachedir}" && return 1; fi
 fi
 
 }
@@ -376,8 +383,41 @@ default_distrib_url () {
 # Helper function for urpmi functions.
 # This is needed to ensure we use a valid remote "distrib" medium. Using MIRRORLIST.
 ####################################################################################################################################################
-error2 "$(gettext "Zeynep needs a repo url to add as a urpmi medium. But none found. Will use 'MIRRORLIST' by default.")"
+if [[ -z ${default_distrib} ]]; then
+    error2 "$(gettext "Zeynep needs a repo url to add as a urpmi medium. But none found. Will use 'MIRRORLIST' by default.")"
+else
+    msg "$(gettext "User forced zeynep to use default distrib urpmi source: MIRRORLIST")"
+fi
+
 run_command "sudo urpmi.addmedia --urpmi-root ${chrootdir} --auto --distrib --mirrorlist \$MIRRORLIST" || ( error "$(gettext "Zeynep can not add default MIRRORLIST distrib source. Zeynep can not continue without a distrib urpmi medium. Please check %s for possible errors. Exiting...")" "${log_file}" && exit_function )
+
+}
+
+####################################################################################################################################################
+care_medias () {
+# We should also think of Nonfree and Tainted medias; give an option to the user for enabling them:
+####################################################################################################################################################
+
+if [[ -n "${no_ignore_media_array[*]}" ]]; then
+    local IFS=""
+    for non_ignored in ${no_ignore_media_array[*]}; do
+        msg "$(gettext "Enabling %s media as urpmi source in chroot environment")" "${non_ignored}"
+        if run_command "sudo urpmi.update --urpmi-root ${chrootdir} --no-ignore ${non_ignored} && sudo urpmi.update --urpmi-root ${chrootdir} -a"; then
+            plain "$(gettext "... DONE!")"
+        else 
+            read -r -p "$(error2 "$(gettext "Zeynep can not enable %s media. Will continue without this media enabled. Do you want to proceed? [y/N]")" "${non_ignored}" )" media_response
+            case $media_response in
+                [yY][eE][sS]|[yY] ) 
+                        echo
+                        ;;
+                *)
+                        
+                        exit_function
+                        ;;
+            esac
+        fi
+    done
+fi
 
 }
 
@@ -386,7 +426,7 @@ urpmi_addmedia () {
 # Add urpmi medias to get package lists and installation medium
 ####################################################################################################################################################
 
-if [[ -n "${distrib_array[*]}" ]]; then
+if [[ -n "${distrib_array[*]}" && -z ${default_distrib} ]]; then
     for distribs in ${distrib_array[*]}; do
         run_command "sudo urpmi.addmedia --urpmi-root ${chrootdir} --distrib ${distribs}/${mga_version}/${arch}" || ( error "$(gettext "Zeynep can not add %s distrib source. Therefore will try the default distrib media source")" "${distribs}" && default_distrib_url )
     done
@@ -416,27 +456,7 @@ if [[ -n "${media_array[*]}" ]]; then
     done
 fi
 
-# We should also think of Nonfree and Tainted medias; give an option to the user for enabling them:
-if [[ -n "${no_ignore_media_array[*]}" ]]; then
-    IFS=""
-    for non_ignored in ${no_ignore_media_array[*]}; do
-        msg "$(gettext "Enabling %s media as urpmi source in chroot environment")" "${non_ignored}"
-        if run_command "sudo urpmi.update --urpmi-root ${chrootdir} --no-ignore ${non_ignored} && sudo urpmi.update --urpmi-root ${chrootdir} -a"; then
-            plain "$(gettext "... DONE!")"
-        else 
-            read -r -p "$(error2 "$(gettext "Zeynep can not enable %s media. Will continue without this media enabled. Do you want to proceed? [y/N]")" "${non_ignored}" )" media_response
-            case $media_response in
-                [yY][eE][sS]|[yY] ) 
-                        echo
-                        ;;
-                *)
-                        
-                        exit_function
-                        ;;
-            esac
-        fi
-    done
-fi
+care_medias
 
 }
 
@@ -489,14 +509,18 @@ urpmi_addmedia
 # Main urpmi install
 msg "$(gettext "Starting to install base packages needed to create a build chroot environment: ")"
 chroot_rpms+=("basesystem-minimal locales rpm-build rpm-mageia-setup-build sudo urpmi rpm-sign curl")
-local packages="${chroot_rpms[@]}"
+local packages="${chroot_rpms[*]}"
 
 # Default urpmi options. Should be stay as is.
 urpmi_options+=("--auto --debug --excludedocs --no-verify-rpm --nolock --ignoresize")
-urpmi_options_array="${urpmi_options[@]}"
+urpmi_options_array="${urpmi_options[*]}"
 
 # Install packages
 ( run_command "sudo urpmi --urpmi-root ${chrootdir} ${urpmi_options_array} ${packages}" && msg "$(gettext "Base packages installation was succesful. Starting to compressing operation")" ) || ( error "$(gettext "Urpmi failed to install base packages in chroot environment. See %s for detailed information")" "${log_file}" && exit_function )
+
+# We should remove leftover medium sources before archiving chroot env.
+msg "$(gettext "Removing configured urpmi sources before compressing chroot directory...")"
+( run_command "sudo urpmi.removemedia --urpmi-root ${chrootdir} -a" && msg "$(gettext "...DONE!")" ) || error2 "$(gettext "Removing urpmi sources failed.")"
 
 }
 
@@ -506,13 +530,16 @@ create_tarball () {
 # Created tarballs will be used for package building
 ####################################################################################################################################################
 
+# First unmount cachedir before archiving or expect that a very big tarball :)
 if mount | grep ${chrootdir}/var/cache/urpmi/rpms; then
-    msg "$(gettext "Unmounting %s before starting to compress chroot environment")" "${chrootdir}/var/cache/urpmi/rpms"
-    ( run_command "sudo umount ${chrootdir}/var/cache/urpmi/rpms" && msg "$(gettext "... DONE!")" ) || ( error "$(gettext "An error occured during unmounting %s. Please unmount manually.")" "${chrootdir}/var/cache/urpmi/rpms" && exit_function )
+    msg "$(gettext "Unmounting %s before starting to compress chroot environment...")" "${chrootdir}/var/cache/urpmi/rpms"
+    ( run_command "sudo umount ${chrootdir}/var/cache/urpmi/rpms" && msg "$(gettext "... DONE! %s has been unmounted")" "${chrootdir}/var/cache/urpmi/rpms" ) || ( error "$(gettext "An error occured during unmounting %s. Please unmount manually.")" "${chrootdir}/var/cache/urpmi/rpms" && exit_function )
 fi
+
+# Push into tempdir and compress chroot directory now.
 run_command "pushd ${tempdir}"
 plain "$(gettext "Starting to create xz compressed tarball:")"
-( run_command "sudo tar cJf $tarball.tar.xz --exclude='*.rpm' chroot" && msg "$(gettext "Zeynep succesfully completed the chroot tarball creation operation. Now you can use it for package building")" ) || ( error "$(gettext "Unable to compress %s as %s . Please check %s for possible errors. Exiting...")" "${chrootdir}" "${tarball}" "${log_file}" && run_command "popd" && exit_function )
+( run_command "sudo tar cJf $tarball.tar.xz --exclude='*.rpm' chroot" && msg "$(gettext "Zeynep succesfully completed the chroot tarball creation operation. Now you can use it for package building")" ) || ( error "$(gettext "Unable to compress %s as %s . Please check %s for possible errors. Exiting...")" "${chrootdir}" "${tarball}.tar.xz" "${log_file}" && run_command "popd" && exit_function )
 run_command "popd"
 
 }
@@ -605,9 +632,6 @@ test_tarball_dir
 # Create chroot directory
 run_command "mkdir -p ${chrootdir}" || ( error "$(gettext "'mkdir' command can not create chroot directory at %s. See %s for possible errors. Exiting...")" "$TMPDIR" "${log_file}" && exit_function )
 
-## Set tarball upload directory as global variable for generate_chroot and sub functions
-#tarball="${tarball_dir}/chroot-mageia-${mga_version}-${arch}"
-
 ## Run sub functions now:
 chroot_urpmi_install
 control_rpmmacros
@@ -639,29 +663,34 @@ unmount_necessary_dirs
 
 ####################################################################################################################################################
 ####################################################################################################################################################
+####################################################################################################################################################
 
 ####################################################################################################################################################
-check_srpm () {
-# Checks if given file is an srpm, else shows error and exits
+package_or_chroot () {
+# Determine if we have an srpm file; if there is an srpm then source config files and run rpm building function
+# If not then source config files and create chroot tarball function
 ####################################################################################################################################################
 
 if [[ -n ${given_srpm} ]]; then
     if [ ${given_srpm: -8} == ".src.rpm" ]; then
         srpm="${given_srpm}"
+        # Get user config values from config files:
+        config_file
+        # Create rpms:
+        build_in_chroot
     else
         error "$(gettext "Given %s file is not an srpm. Please supply a valid srpm and try again. Exiting...")" "${given_srpm}" && exit 1
     fi
 else
-    [[ -n ${generate_tarball} ]] || ( error "$(gettext "You must supply a srpm file to build rpm packages using zeynep but none given. Exiting...")" && exit 1 )
+    if [[ -n ${generate_tarball} ]]; then
+        # Get user config values from config files:
+        config_file
+        # Create tarballs
+        generate_chroot
+    else
+        ( error "$(gettext "You must supply a srpm file to build rpm packages using zeynep but none given.\nOr do you forget to use '-s' switch? Exiting...")" && exit 1 )
+    fi
 fi
-
-}
-
-####################################################################################################################################################
-package_or_chroot () {
-# Determine if we create chroot tarball or build rpm packages.
-####################################################################################################################################################
-if [[ -z ${generate_tarball} ]]; then build_in_chroot; else generate_chroot; fi
 
 }
 
@@ -681,12 +710,12 @@ if [[ -n ${MGAARCH} ]]; then
     elif [ $(arch) != "x86_64" ] && [ ${MGAARCH} == "i586" ]; then
         export arch="i586" && package_or_chroot 
     elif [ ${MGAARCH} == "both" ]; then
-        unset arch
-        export arch="i586" && package_or_chroot
-        export arch="x86_64" && package_or_chroot
+        unset arch && export arch="i586" && package_or_chroot
+        msg "$(gettext "\nZeynep will try to create package/tarball for x86_64 system now.\n")"
+        unset arch && export arch="x86_64" && package_or_chroot
     fi
 else
-    warning "$(gettext "You have specified an invalid/null argument for system architecture. Zeynep will build packages/tarballs for your system's main architecture")"
+    warning "$(gettext "You have specified an invalid argument for system architecture. Zeynep will build packages/tarballs for your system's main architecture")"
     if [ $(arch) != "x86_64" ]; then export arch="i586" && package_or_chroot; else export arch="x86_64" && package_or_chroot; fi
 fi
 
@@ -760,10 +789,6 @@ update_rpms () {
 # Check if user wants to use rpm cache:
 if cache_option; then urpmi_options+=("--noclean"); fi
 
-# Rebuild rpm database in chroot environment
-msg "$(gettext "Rebuilding RPM database. Please wait a few seconds...")"
-( su_in_chroot "rpm --rebuilddb" && msg "$(gettext "... DONE!")" ) || error "$(gettext "Zeynep failed to rebuild rpm database. Will try without this. But expect errors.")"
-
 # Update rpms in chroot (There would be updated packages after chroot tarball creation)
 msg "$(gettext "There may be updated packages after chroot tarball creation. Zeynep will try to update chroot system. Please wait a few seconds...")"
 if su_in_chroot "urpmi --auto --auto-update"; then
@@ -780,6 +805,10 @@ else
                         ;;
     esac
 fi
+
+# Rebuild rpm database in chroot environment
+msg "$(gettext "Rebuilding RPM database. Please wait a few seconds...")"
+( su_in_chroot "rpm --rebuilddb" && msg "$(gettext "... DONE!")" ) || error "$(gettext "Zeynep failed to rebuild rpm database. Will try without this. But expect errors.")"
 
 }
 
@@ -966,8 +995,9 @@ unmount_necessary_dirs
 #S: sign compiled rpms via rpm-sign
 #G: generate hdlists via genhdlist2
 #h: help
+
 passed_options=0
-while getopts ":gCTNvVlSGhm:D:d:c:M:n:u:a:U:t:p:s:" OPTION ; do
+while getopts ":gCTNvVlSGhzm:D:d:c:M:n:u:a:U:t:p:s:" OPTION ; do
     passed_options=1
 	case ${OPTION} in
 		m)
@@ -1038,6 +1068,9 @@ while getopts ":gCTNvVlSGhm:D:d:c:M:n:u:a:U:t:p:s:" OPTION ; do
 		    ;;		
 		G)
 		    genhdlist="1"
+		    ;;		
+		z)
+		    default_distrib="1"
 		    ;;		    
 		h)
 		    usage && exit 0
@@ -1073,6 +1106,12 @@ if [[ -z ${mga_version} ]]; then
     mga_version="cauldron"
 fi
 
-config_file
-check_srpm
-check_system_arch
+# Preliminary checks
+if [[ -n ${MGAARCH} ]]; then    
+    check_system_arch
+else
+    warning "$(gettext "You have specified no argument for system architecture. Zeynep will build packages/tarballs for your system's main architecture")"
+    if [ $(arch) != "x86_64" ]; then MGAARCH="i586" && check_system_arch; else MGAARCH="x86_64" && check_system_arch; fi
+fi
+
+
