- Add seperators between functions for easy reading - Fix some misspellings - Take trap_function_for_tarball function into generate_chroot function

diff --git a/src/zeynep-tarball-creator b/src/zeynep-tarball-creator
--- a/src/zeynep-tarball-creator
+++ b/src/zeynep-tarball-creator
@@ -21,6 +21,9 @@ use_cache="1"
 use_rpm_macros="1"
 ################################################
 
+
+####################################################################################################################################################
+# Coloring our messages (Thanks to Arch Linux & pacman dev team)
 # check if messages are to be printed using color
 unset ALL_OFF BOLD BLUE GREEN RED YELLOW
 # prefer terminal safe colored and bold text when tput is supported
@@ -41,70 +44,96 @@ else
 fi
 readonly ALL_OFF BOLD BLUE GREEN RED YELLOW
 
-plain () {
-# Funtion to display localized plain messages
-	local mesg=$1; shift
-	printf "${BOLD}    ${mesg}${ALL_OFF}\n" "$@" >&2
-}
-
-msg () {
-# Funtion to display localized and colorized information messages
-	local mesg=$1; shift
-	printf "${GREEN}==>$(gettext "INFO :: ")${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@" >&2
-}
-
-error2 () {
-# Funtion to display localized and colorized information messages
-	local mesg=$1; shift
-	printf "${RED}==>$(gettext "NOT CRITICAL ERROR :: ")${ALL_OFF}${BOLD}${YELLOW} ${mesg}${ALL_OFF}\n" "$@" >&2
-}
-
-warning () {
-# Funtion to display localized and colorized warning messages
-	local mesg=$1; shift
-	printf "${YELLOW}==> $(gettext "WARNING :: ")${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@" >&2
-}
-
-error () {
-# Funtion to display localized and colorized error messages
-	local mesg=$1; shift
-	printf "${RED}==> $(gettext "ERROR :: ")${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@" >&2
-}
-
-run_command () {
-# Runs bash command and sends all output to /dev/null
-    local command=$1; shift
-    ${command} > /dev/null 2>&1
-}
-
-tidy_rpms () {
-# Global function to tidy downloaded rpms either in cache directory or rpm upload directory for future use
-tidy_dir=$1
-if [[ -n "$tidy_rpms" ]]; then rpm-tidy -f --dir="$tidy_dir"; fi
-
-}
-
-trap_function () {
-# Cleans up build directories
-run_command "sudo umount $chrootdir/{dev/pts,dev,proc,sys,var/cache/urpmi/rpms}"
-}
-
-#trap "control_c; exit" SIGINT SIGTERM SIGHUP
-
-# Create log file
+####################################################################################################################################################
+# Log file creation.
+# I have tried infamous (exec > tee) stuff. Unfortunately i couldn't manage traps to work. This is the only working way that i' ve found:
+####################################################################################################################################################
 log_file="$(mktemp -t --suffix=".log" zeynep-builder.XXXXXXXXXX )"
 mkfifo ${log_file}.pipe
 tee < ${log_file}.pipe $log_file &
 exec &> ${log_file}.pipe
 
+####################################################################################################################################################
+plain () {
+# Funtion to display localized plain messages
+####################################################################################################################################################
+	local mesg=$1; shift
+	printf "${BOLD}    ${mesg}${ALL_OFF}\n" "$@" >&2
+}
+
+####################################################################################################################################################
+msg () {
+# Funtion to display localized and colorized information messages
+####################################################################################################################################################
+	local mesg=$1; shift
+	printf "${GREEN}==>$(gettext "INFO :: ")${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@" >&2
+}
+
+####################################################################################################################################################
+error2 () {
+# Function to display localized and colorized information messages
+####################################################################################################################################################
+	local mesg=$1; shift
+	printf "${RED}==>$(gettext "NOT CRITICAL ERROR :: ")${ALL_OFF}${BOLD}${YELLOW} ${mesg}${ALL_OFF}\n" "$@" >&2
+}
+
+####################################################################################################################################################
+warning () {
+# Funtion to display localized and colorized warning messages
+####################################################################################################################################################
+	local mesg=$1; shift
+	printf "${YELLOW}==> $(gettext "WARNING :: ")${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@" >&2
+}
+
+####################################################################################################################################################
+error () {
+# Funtion to display localized and colorized error messages
+####################################################################################################################################################
+	local mesg=$1; shift
+	printf "${RED}==> $(gettext "ERROR :: ")${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@" >&2
+}
+
+####################################################################################################################################################
+run_command () {
+# Runs bash command and sends all output to /dev/null
+# It may be bad but i prefer hide them.
+####################################################################################################################################################
+    local command=$1; shift
+    ${command} > /dev/null 2>&1
+}
+
+####################################################################################################################################################
+tidy_rpms () {
+# Global function to tidy downloaded rpms either in cache directory or rpm upload directory for future use
+####################################################################################################################################################
+tidy_dir=$1
+if [[ -n "$tidy_rpms" ]]; then rpm-tidy -f --dir="$tidy_dir"; fi
+
+}
+
+####################################################################################################################################################
+trap_function () {
+# Cleans up build directories
+####################################################################################################################################################
+run_command "sudo umount $chrootdir/{dev/pts,dev,proc,sys,var/cache/urpmi/rpms}"
+}
+
+#trap "control_c; exit" SIGINT SIGTERM SIGHUP
+
+
+####################################################################################################################################################
 tidy_log_file () {
 # Helper function to clean up and tidy logfile:
+# Currently not working, see this as a placeholder
+####################################################################################################################################################
 sed -i "s|^[[1m^[[32m||g" $log_file
 }
 
+####################################################################################################################################################
 control_rpmmacros () {
 # Check if user wants to include rpmmacros file.
 # Also, user can use his $HOME/.rpmmacros
+####################################################################################################################################################
 if [[ -n $use_rpm_macros ]]; then
     if [[ -f $HOME/.rpmmacros ]]; then
         run_command "sudo cp -f ${HOME}/.rpmmacros ${chrootdir}/etc/skel/" || error "$(gettext "Specified rpmmacros file can not be copied")"
@@ -114,16 +143,21 @@ if [[ -n $use_rpm_macros ]]; then
 fi
 }
 
+####################################################################################################################################################
 standalone_urpmi_install_in_chroot_creation () {
 # Main basesystem installation function into newly created chroot
 # Helper function to chroot_urpmi_install function
+####################################################################################################################################################
 msg "$(gettext "Starting to install base packages needed to create a build chroot environment")"
-sudo urpmi $urpmi_options --urpmi-root $chrootdir --auto --no-recommends --excludedocs --no-verify-rpm --nolock --ignoresize basesystem-minimal locales locales-en rpm-build rpm-mageia-setup-build sudo urpmi rpm-sign curl || ( error "$(gettext "Urpmi failed to install base packages in chroot environment. See %s for detailed information")" "$log_file" && exit 1 )
+sudo urpmi ${urpmi_options} --urpmi-root ${chrootdir} --auto --no-recommends --excludedocs --no-verify-rpm --nolock --ignoresize basesystem-minimal locales locales-en rpm-build rpm-mageia-setup-build sudo urpmi rpm-sign curl || ( error "$(gettext "Urpmi failed to install base packages in chroot environment. See %s for detailed information")" "${log_file}" && exit 1 )
 
 }
 
+####################################################################################################################################################
 chroot_urpmi_install () {
-# Check if user wants to use cache option:
+# Main package installation function in chroot
+# Check if user wants to use cache option. If cache is not used run standalone_urpmi_install_in_chroot_function:
+####################################################################################################################################################
 if [[ -n ${use_cache} && -d $cachedir ]];then
     run_command "sudo mkdir -p ${chrootdir}/var/cache/urpmi/rpms" || ( error "$(gettext "Failed to create mandatory %s directory")" "$chrootdir/var/cache/urpmi/rpms" && standalone_urpmi_install_in_chroot_creation)
     run_command "sudo mount -R ${cachedir} ${chrootdir}/var/cache/urpmi/rpms" || ( error "$(gettext "Failed to mount %s.")" "$cachedir" && ( run_command "umount $chrootdir/var/cache/urpmi/rpms" ||  error "$(gettext "Can not unmount cache directory from %s. Please do it manually.")" "$chrootdir/var/cache/urpmi/rpms") && exit 1 )
@@ -135,9 +169,11 @@ fi
 
 }
 
+####################################################################################################################################################
 create_tarball () {
 # Creates xz compressed tarball from chroot directory.
 # Created tarballs will be used for package building
+####################################################################################################################################################
 
 if [[ -n ${use_cache} && -d $cachedir ]];then
     msg "$(gettext "Unmounting %s")" "${chrootdir}/var/cache/urpmi/rpms"
@@ -149,17 +185,22 @@ popd
 
 }
 
+####################################################################################################################################################
 create_installed_rpms_list () {
-# Create a sorted lis of installed rpm packages in chroot
+# Create a sorted list of installed rpm packages in chroot.
+####################################################################################################################################################
+
 rpm_query_tags="%{NAME}:%{VERSION}:%{RELEASE}:%{SOURCERPM}\n"
 rpms_list="$chroot_directory/$tarball-rpms.lst"
 run_command "sudo rpm -r ${chrootdir} -qa --queryformat ${rpm_query_tags} | sort > ${rpms_list}" || error "$(gettext "Can not export installed rpms to %s.Will continue without creating it")" "$rpms_list"
 
 }
-
+####################################################################################################################################################
 new_name_tarball () {
 # Helper function for overwrite_tarball function
 # Ask user for new tarball name.
+####################################################################################################################################################
+
 read -r -p "$(plain "$(gettext "Please enter a name for chroot-tarball without any extension: ")")" new_tarball_name
 if [[ -n ${new_tarball_name} ]]; then
     export tarball="$chroot_directory/$new_tarball_name"
@@ -167,9 +208,12 @@ else
     error "$(gettext "You did not give a name for chroot-tarball! Zeynep could not create a blank named tarball. Exiting... ")" && exit 1
 fi
 }
+
+####################################################################################################################################################
 overwrite_tarball () {
 # Ask user if he wants to overwrite to previous tarball.
 # If user does not want to overwrite exit with information message
+####################################################################################################################################################
 
 read -r -p "$(plain "$(gettext "Do you want to overwrite old tarball with the new one? [Y/n]")")" response
 case $response in
@@ -184,8 +228,10 @@ esac
 
 }
 
+####################################################################################################################################################
 test_tarballs () {
 # Test tarballs existance. If found create a backup directory and move them there before overwriting.
+####################################################################################################################################################
 
 if [[ -f "$tarball.tar.xz" ]]; then
     msg "$(gettext "Previously created %s tarball found. Zeynep will backup it. You can find it in %s directory")" "$tarball.tar.xz" "${chroot_directory}/zeynep_backups"
@@ -200,8 +246,11 @@ fi
 
 }
 
+####################################################################################################################################################
 test_chroot_dir ()  {
 # Test if chroot directory is given; if not show error and exit
+####################################################################################################################################################
+
 if [[ -z ${chroot_directory} ]]; then
     error "$(gettext "You tried to create a chroot tarball but did not provide a path where tarball(s) will created in. 
 Please check %s for possible errors. Exiting...")" "$log_file"
@@ -215,8 +264,10 @@ fi
 
 }
 
+####################################################################################################################################################
 trap_function_for_tarball () {
 # Function to use in traps in generating chroot phase.
+####################################################################################################################################################
 
 msg "$(gettext "User aborted the operation. Cleaning up and exiting... ")"
 if mount | grep ${chrootdir}/var/cache/urpmi/rpms; then
@@ -230,8 +281,11 @@ exit $?
 
 }
 
+####################################################################################################################################################
 generate_chroot () {
+# Main chroot environment and tarball creation function.
 # Create chroot environment and install basesystem + other required packages
+####################################################################################################################################################
 
 tempdir="$(mktemp -dt zeynep-chroot-XXXX)"
 chrootdir="$tempdir/chroot"
@@ -254,13 +308,14 @@ control_rpmmacros
 create_installed_rpms_list
 test_tarballs
 tidy_rpms "$cachedir"
-
+# We should clean our mess :)
+trap_function_for_tarball
 
 }
 
 generate_chroot
 
-# We should clean our mess :)
-trap_function_for_tarball
+
+
 
 
